2023-10-04 13:33:08,972:INFO:strategy:init_strategy_csv_log:Strategy:500:added csv row to csv_files/strategy_20231004.csv
2023-10-04 13:33:08,973:INFO:strategy:init_strategy_json:Strategy:301:read previous not empty strategy state from json_files/strategy_20231004.json
2023-10-04 13:33:08,973:INFO:strategy:initialise_logs_n_files:Strategy:301:logs and json initialised
2023-10-04 13:33:10,529:INFO:strategy:update:Strategy:301: exception
2023-10-04 13:33:10,529:ERROR:strategy:update:name 'test_prints' is not defined
Traceback (most recent call last):
  File "/Users/anirudh/Documents/lunar/strategy.py", line 631, in update
    self.initialise()
  File "/Users/anirudh/Documents/lunar/strategy.py", line 615, in initialise
    self._set_dataprocessor_obj()
  File "/Users/anirudh/Documents/lunar/strategy.py", line 107, in _set_dataprocessor_obj
    self.nf_fut_obj = FnoDataProcessor(self.kite_obj, nf_fut_token, self.candle_interval, None, self.logger)
  File "/Users/anirudh/Documents/lunar/fnodataprocessor.py", line 70, in __init__
    test_prints(f"{__class__.__name__}, instruToken: {self.instru_token}, instruSymbol: {self.trading_symbol}, object created")
NameError: name 'test_prints' is not defined
